version: '3'

services:
  sub:
    image: mongmx/thruster-engine:latest
    environment:
      - APP_ENV=${APP_ENV}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
    env_file:
      - ./.env
    deploy:
      replicas: 3
